# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Chans 기술블로그
email: pcswer@gmail.com
description: "프론트엔드 기술블로그 사이트"
baseurl: "" # the subpath of your site, e.g. /blog
# url: ""
url: "https://chanspark.github.io"
author: "Chans"
# twitter_username: jekyllrb
github_username: chanspark
timezone: Asia/Seoul

asset_path: "/assets/" # assets의 경로
# asset_path: "/assets/" # assets의 경로
image: '/assets/main_photo.jpg'

keep_files: [assets]

# jekyll-seo-tag options
logo : "/assets/images/chans.png"

# Build settings
markdown: kramdown
mgems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
gems: 
  - jekyll-seo-tag 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
#   - jekyll-autoprefixer

# 태그 기능
collections:
  tags:
    output: true
    permalink: /tags/:path/

defaults:
  - 
    scope:
      path: ''
      type: tags
    values:
      layout: tag

# Disqus
disqus:
  shortname: "chanspark-blog"

#google analytics
google_analytics: true

#pagination
paginate: 5
paginate_path: "/page:num"

# Sass settings
#sass:
#    sass_dir: _sass
#    style: :compressed

# SEO
social:
  name: Chans Park
  links:
    - https://github.com/chanspark
